# Generated by Django 5.2.15 on 2026-06-12 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('terrain', models.CharField(choices=[('water', 'Вода'), ('land', 'Суша')], max_length=10)),
                ('nutrients', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'ordering': ['y', 'x'],
                'unique_together': {('x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_type', models.CharField(choices=[('microbe', 'Одноклеточное'), ('multicellular', 'Многоклеточное'), ('plant', 'Растение'), ('fungi', 'Мицелий'), ('worm', 'Червь'), ('tetrapod', 'Тетрапод')], default='microbe', max_length=20)),
                ('alive', models.BooleanField(default=True)),
                ('energy', models.FloatField(default=12.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('reserve', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('trait', models.IntegerField(blank=True, choices=[(1, 'Выносливость'), (2, 'Быстрое накопление'), (3, 'Каннибализм'), (4, 'Синергия'), (5, 'Аккумулятор')], null=True)),
                ('enhancement', models.CharField(blank=True, choices=[('A', 'Плодовитость'), ('B', 'Гигантизм'), ('C', 'Сложность'), ('D', 'Скорость')], max_length=5, null=True)),
                ('behavior', models.CharField(blank=True, choices=[('predator', 'Хищник'), ('scavenger', 'Падальщик'), ('generalist', 'Универсал')], max_length=15, null=True)),
                ('cell_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('speed', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('birth_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('death_hour', models.IntegerField(blank=True, null=True)),
                ('death_cause', models.CharField(blank=True, max_length=20, null=True)),
                ('cannibal_hour', models.IntegerField(blank=True, null=True)),
                ('run_id', models.IntegerField(default=1)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisms', to='core.cell')),
            ],
            options={
                'verbose_name': 'Организм',
                'verbose_name_plural': 'Организмы',
                'indexes': [models.Index(fields=['alive'], name='core_organi_alive_b8d472_idx'), models.Index(fields=['cell'], name='core_organi_cell_id_600a25_idx'), models.Index(fields=['run_id'], name='core_organi_run_id_f247d4_idx'), models.Index(fields=['organism_type', 'alive'], name='core_organi_organis_638b20_idx')],
            },
        ),
    ]
