# Generated by Django 5.2.15 on 2026-06-12 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField(default=1)),
                ('organism_type', models.CharField(max_length=20)),
                ('trait', models.IntegerField(blank=True, null=True)),
                ('energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('cause', models.CharField(max_length=20)),
                ('hour_of_death', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eaten', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Мёртвый организм',
                'verbose_name_plural': 'Мёртвые организмы',
                'indexes': [models.Index(fields=['eaten'], name='core_deador_eaten_74f779_idx'), models.Index(fields=['x', 'y'], name='core_deador_x_18859e_idx'), models.Index(fields=['run_id'], name='core_deador_run_id_680f20_idx')],
            },
        ),
    ]
