# Generated by Django 5.2.15 on 2026-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deadorganism'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField(default=1)),
                ('hour', models.IntegerField()),
                ('event_type', models.CharField(choices=[('birth', 'Рождение'), ('death', 'Смерть'), ('division', 'Деление'), ('fusion', 'Слияние'), ('migration', 'Миграция'), ('mutation', 'Мутация'), ('storm_kill', 'Гибель от бури'), ('weather', 'Погодное событие'), ('first_multicellular', 'Первый многоклеточный'), ('first_land', 'Первый выход на сушу'), ('extinction', 'Вымирание')], max_length=30)),
                ('organism_id', models.IntegerField(blank=True, null=True)),
                ('organism_type', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'indexes': [models.Index(fields=['run_id', 'hour'], name='core_eventl_run_id_55601a_idx'), models.Index(fields=['event_type'], name='core_eventl_event_t_d54e87_idx')],
            },
        ),
    ]
