# Generated by Django 5.2.15 on 2026-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField(unique=True)),
                ('map_width', models.IntegerField(default=30)),
                ('map_height', models.IntegerField(default=20)),
                ('water_ratio', models.FloatField(default=0.5)),
                ('microbe_spawn_chance', models.FloatField(default=0.3)),
                ('trait_chance', models.FloatField(default=0.35)),
                ('max_microbes_for_spawn', models.IntegerField(default=255)),
                ('microbe_division_threshold', models.FloatField(default=24)),
                ('microbe_min_age', models.IntegerField(default=24)),
                ('microbe_max_age', models.IntegerField(default=72)),
                ('fusion_chance', models.FloatField(default=0.03)),
                ('multicell_division_threshold', models.FloatField(default=255)),
                ('fertility_threshold', models.FloatField(default=200)),
                ('enhancement_mutation_chance', models.FloatField(default=0.15)),
                ('cell_capacity', models.IntegerField(default=100)),
                ('crowding_chain_length', models.IntegerField(default=5)),
                ('storm_temp_threshold', models.FloatField(default=30)),
                ('storm_death_chance', models.FloatField(default=0.1)),
                ('humidity_per_plant', models.FloatField(default=1.0)),
                ('temp_per_land_creature', models.FloatField(default=1.0)),
                ('nutrient_migration_factor', models.FloatField(default=1.0)),
                ('cannibal_migration_factor', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Конфигурация запуска',
                'verbose_name_plural': 'Конфигурации запусков',
            },
        ),
        migrations.CreateModel(
            name='RunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('total_hours', models.IntegerField(null=True)),
                ('final_microbes', models.IntegerField(null=True)),
                ('final_multicellular', models.IntegerField(null=True)),
                ('final_plants', models.IntegerField(null=True)),
                ('final_fungi', models.IntegerField(null=True)),
                ('final_worms', models.IntegerField(null=True)),
                ('final_tetrapods', models.IntegerField(null=True)),
                ('max_diversity', models.IntegerField(null=True)),
                ('dominant_form', models.CharField(max_length=20, null=True)),
                ('first_multicellular_hour', models.IntegerField(null=True)),
                ('first_land_hour', models.IntegerField(null=True)),
                ('first_plant_hour', models.IntegerField(null=True)),
                ('first_tetrapod_hour', models.IntegerField(null=True)),
                ('max_temperature', models.FloatField(null=True)),
                ('max_humidity', models.FloatField(null=True)),
                ('total_storms', models.IntegerField(default=0)),
                ('total_deaths_by_storm', models.IntegerField(default=0)),
                ('extinction_hour', models.IntegerField(null=True)),
                ('extinction_cause', models.CharField(max_length=50, null=True)),
                ('timeline_24h', models.JSONField(null=True)),
                ('unique_events', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сводка запуска',
                'verbose_name_plural': 'Сводки запусков',
            },
        ),
    ]
